export const stylesDictionary = {
    // Backgrounds
    "chai-bg-transparent": "background-color: transparent",
    "chai-bg-current": "background-color: currentColor",
    "chai-bg-white": "background-color: white",
    "chai-bg-black": "background-color: black",
    "chai-bg-red": "background-color: red",
    "chai-bg-green": "background-color: green",
    "chai-bg-blue": "background-color: blue",
    "chai-bg-orange": "background-color: orange",
    "chai-bg-yellow": "background-color: yellow",
    "chai-bg-purple": "background-color: purple",
    "chai-bg-pink": "background-color: pink",
    "chai-bg-slate": "background-color: #64748b",
    "chai-bg-subtle-dark": "background-color: #292929",
    "chai-bg-cover": "background-size: cover",
    "chai-bg-contain": "background-size: contain",
    "chai-bg-center": "background-position: center",
    "chai-bg-top": "background-position: top",
    "chai-bg-bottom": "background-position: bottom",
    "chai-bg-left": "background-position: left",
    "chai-bg-right": "background-position: right",
    "chai-bg-no-repeat": "background-repeat: no-repeat",
    "chai-bg-repeat": "background-repeat: repeat",

    // Typography
    "chai-sans": "font-family: ui-sans-serif, system-ui, sans-serif",
    "chai-serif": "font-family: ui-serif, Georgia, serif",
    "chai-mono": "font-family: ui-monospace, SFMono-Regular, monospace",
    "chai-font-dm-sans": "font-family: 'DM Sans', sans-serif",
    "chai-font-fraunces": "font-family: 'Fraunces', serif",
    "chai-font-fira": "font-family: 'Fira Code', monospace",
    "chai-uppercase": "text-transform: uppercase",
    "chai-lowercase": "text-transform: lowercase",
    "chai-capitalize": "text-transform: capitalize",
    "chai-normal-case": "text-transform: none",
    "chai-italic": "font-style: italic",
    "chai-not-italic": "font-style: normal",
    "chai-underline": "text-decoration: underline",
    "chai-line-through": "text-decoration: line-through",
    "chai-no-underline": "text-decoration: none",
    "chai-text-xs": "font-size: 12px",
    "chai-text-sm": "font-size: 14px",
    "chai-text-md": "font-size: 16px",
    "chai-text-lg": "font-size: 18px",
    "chai-text-xl": "font-size: 20px",
    "chai-text-2xl": "font-size: 24px",
    "chai-text-3xl": "font-size: 30px",
    "chai-text-4xl": "font-size: 36px",
    "chai-text-5xl": "font-size: 42px",
    "chai-text-6xl": "font-size: 48px",
    "chai-leading-none": "line-height: 1",
    "chai-leading-tight": "line-height: 1.1",
    "chai-leading-snug": "line-height: 1.375",
    "chai-leading-normal": "line-height: 1.5",
    "chai-leading-relaxed": "line-height: 1.625",
    "chai-leading-loose": "line-height: 2",
    "chai-tracking-tight": "letter-spacing: -0.025em",
    "chai-tracking-normal": "letter-spacing: 0",
    "chai-tracking-wide": "letter-spacing: 0.025em",
    "chai-tracking-wider": "letter-spacing: 0.05em",
    "chai-tracking-widest": "letter-spacing: 0.1em",
    "chai-font-thin": "font-weight: 100",
    "chai-font-light": "font-weight: 300",
    "chai-font-normal": "font-weight: 400",
    "chai-font-medium": "font-weight: 500",
    "chai-font-semibold": "font-weight: 600",
    "chai-font-bold": "font-weight: 700",
    "chai-font-extrabold": "font-weight: 800",
    "chai-font-black": "font-weight: 900",
    "chai-text-left": "text-align: left",
    "chai-text-center": "text-align: center",
    "chai-text-right": "text-align: right",
    "chai-text-justify": "text-align: justify",
    "chai-text-black": "color: black",
    "chai-text-white": "color: white",
    "chai-text-red": "color: red",
    "chai-text-orange": "color: orange",
    "chai-text-yellow": "color: yellow",
    "chai-text-green": "color: green",
    "chai-text-blue": "color: blue",
    "chai-text-purple": "color: purple",
    "chai-text-pink": "color: pink",
    "chai-text-slate": "color: #64748b",
    "chai-antialiased": "-webkit-font-smoothing: antialiased; -moz-osx-font-smoothing: grayscale",
    "chai-truncate": "overflow: hidden; text-overflow: ellipsis; white-space: nowrap",
    "chai-break-words": "overflow-wrap: break-word",
    "chai-break-all": "word-break: break-all",

    // Borders
    "chai-rounded-none": "border-radius: 0",
    "chai-rounded-xs": "border-radius: 2px",
    "chai-rounded-sm": "border-radius: 4px",
    "chai-rounded-md": "border-radius: 6px",
    "chai-rounded-lg": "border-radius: 8px",
    "chai-rounded-xl": "border-radius: 12px",
    "chai-rounded-2xl": "border-radius: 16px",
    "chai-rounded-3xl": "border-radius: 24px",
    "chai-rounded-4xl": "border-radius: 32px",
    "chai-rounded-full": "border-radius: 9999px",
    "chai-border-white": "border-color: white",
    "chai-border-black": "border-color: black",
    "chai-border-red": "border-color: red",
    "chai-border-green": "border-color: green",
    "chai-border-blue": "border-color: blue",
    "chai-border-slate": "border-color: #64748b",
    "chai-border-subtle": "border-color: #292929",
    "chai-border-solid": "border-style: solid",
    "chai-border-dashed": "border-style: dashed",
    "chai-border-dotted": "border-style: dotted",
    "chai-border-double": "border-style: double",
    "chai-border-none": "border-style: none",

    // Display and position
    "chai-block": "display: block",
    "chai-inline": "display: inline",
    "chai-inline-block": "display: inline-block",
    "chai-inline-flex": "display: inline-flex",
    "chai-inline-grid": "display: inline-grid",
    "chai-hidden": "display: none",
    "chai-relative": "position: relative",
    "chai-absolute": "position: absolute",
    "chai-fixed": "position: fixed",
    "chai-sticky": "position: sticky",
    "chai-static": "position: static",
    "chai-top-auto": "top: auto",
    "chai-right-auto": "right: auto",
    "chai-bottom-auto": "bottom: auto",
    "chai-left-auto": "left: auto",
    "chai-isolate": "isolation: isolate",

    // Overflow and interaction
    "chai-overflow-hidden": "overflow: hidden",
    "chai-overflow-auto": "overflow: auto",
    "chai-overflow-scroll": "overflow: scroll",
    "chai-overflow-visible": "overflow: visible",
    "chai-overflow-x-auto": "overflow-x: auto",
    "chai-overflow-x-hidden": "overflow-x: hidden",
    "chai-overflow-y-auto": "overflow-y: auto",
    "chai-overflow-y-hidden": "overflow-y: hidden",
    "chai-cursor-pointer": "cursor: pointer",
    "chai-cursor-default": "cursor: default",
    "chai-cursor-not-allowed": "cursor: not-allowed",
    "chai-select-none": "user-select: none",
    "chai-select-text": "user-select: text",
    "chai-pointer-events-none": "pointer-events: none",
    "chai-pointer-events-auto": "pointer-events: auto",
    "chai-appearance-none": "appearance: none",
    "chai-outline-none": "outline: none",

    // Box model and scroll
    "chai-box-border": "box-sizing: border-box",
    "chai-box-content": "box-sizing: content-box",
    "chai-scroll-smooth": "scroll-behavior: smooth",
    "chai-scroll-auto": "scroll-behavior: auto",

    // Effects
    "chai-shadow-none": "box-shadow: none",
    "chai-shadow-xs": "box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    "chai-shadow-sm": "box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
    "chai-shadow-md": "box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
    "chai-shadow-lg": "box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)",
    "chai-shadow-xl": "box-shadow: 0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
    "chai-text-shadow-xs": "text-shadow: 0 1px 2px rgba(0, 0, 0, 0.05)",
    "chai-text-shadow-sm": "text-shadow: 0 1px 3px rgba(0, 0, 0, 0.1)",
    "chai-text-shadow-md": "text-shadow: 0 4px 6px rgba(0, 0, 0, 0.1)",
    "chai-text-shadow-lg": "text-shadow: 0 10px 15px rgba(0, 0, 0, 0.1)",
    "chai-text-shadow-xl": "text-shadow: 0 20px 25px rgba(0, 0, 0, 0.1)",
    "chai-opacity-0": "opacity: 0",
    "chai-opacity-25": "opacity: 0.25",
    "chai-opacity-50": "opacity: 0.5",
    "chai-opacity-75": "opacity: 0.75",
    "chai-opacity-100": "opacity: 1",
    "chai-blur-sm": "filter: blur(4px)",
    "chai-blur-md": "filter: blur(8px)",
    "chai-blur-lg": "filter: blur(12px)",
    "chai-grayscale": "filter: grayscale(1)",
    "chai-sepia": "filter: sepia(1)",
    "chai-backdrop-blur-sm": "backdrop-filter: blur(4px)",
    "chai-backdrop-blur-md": "backdrop-filter: blur(8px)",

    // Flexbox and grid
    "chai-flex": "display: flex",
    "chai-grid": "display: grid",
    "chai-flex-row": "flex-direction: row",
    "chai-flex-row-reverse": "flex-direction: row-reverse",
    "chai-flex-column": "flex-direction: column",
    "chai-flex-column-reverse": "flex-direction: column-reverse",
    "chai-flex-wrap": "flex-wrap: wrap",
    "chai-flex-wrap-reverse": "flex-wrap: wrap-reverse",
    "chai-flex-nowrap": "flex-wrap: nowrap",
    "chai-justify-start": "justify-content: flex-start",
    "chai-justify-end": "justify-content: flex-end",
    "chai-justify-center": "justify-content: center",
    "chai-justify-between": "justify-content: space-between",
    "chai-justify-around": "justify-content: space-around",
    "chai-justify-evenly": "justify-content: space-evenly",
    "chai-justify-stretch": "justify-content: stretch",
    "chai-justify-items-start": "justify-items: start",
    "chai-justify-items-end": "justify-items: end",
    "chai-justify-items-center": "justify-items: center",
    "chai-justify-items-stretch": "justify-items: stretch",
    "chai-items-start": "align-items: flex-start",
    "chai-items-end": "align-items: flex-end",
    "chai-items-center": "align-items: center",
    "chai-items-baseline": "align-items: baseline",
    "chai-items-stretch": "align-items: stretch",
    "chai-self-auto": "align-self: auto",
    "chai-self-start": "align-self: flex-start",
    "chai-self-end": "align-self: flex-end",
    "chai-self-center": "align-self: center",
    "chai-self-stretch": "align-self: stretch",
    "chai-content-center": "align-content: center",
    "chai-content-start": "align-content: flex-start",
    "chai-content-end": "align-content: flex-end",
    "chai-content-between": "align-content: space-between",
    "chai-content-around": "align-content: space-around",
    "chai-content-stretch": "align-content: stretch",
    "chai-place-items-center": "place-items: center",
    "chai-place-content-center": "place-content: center",

    // Sizing
    "chai-w-auto": "width: auto",
    "chai-w-full": "width: 100%",
    "chai-w-screen": "width: 100vw",
    "chai-h-auto": "height: auto",
    "chai-h-full": "height: 100%",
    "chai-h-screen": "height: 100vh",
    "chai-min-w-0": "min-width: 0",
    "chai-min-h-0": "min-height: 0",
    "chai-max-w-full": "max-width: 100%",
    "chai-max-h-full": "max-height: 100%",
    "chai-mx-auto": "margin-left: auto; margin-right: auto",
    "chai-my-auto": "margin-top: auto; margin-bottom: auto",

    // Transforms and transitions
    "chai-transform": "transform: translateZ(0)",
    "chai-origin-center": "transform-origin: center",
    "chai-origin-top": "transform-origin: top",
    "chai-origin-bottom": "transform-origin: bottom",
    "chai-transition": "transition-property: all; transition-duration: 150ms; transition-timing-function: ease",
    "chai-transition-colors": "transition-property: color, background-color, border-color, text-decoration-color, fill, stroke; transition-duration: 150ms; transition-timing-function: ease",
    "chai-transition-transform": "transition-property: transform; transition-duration: 150ms; transition-timing-function: ease",
    "chai-duration-75": "transition-duration: 75ms",
    "chai-duration-150": "transition-duration: 150ms",
    "chai-duration-300": "transition-duration: 300ms",
    "chai-duration-500": "transition-duration: 500ms",
    "chai-ease-linear": "transition-timing-function: linear",
    "chai-ease-in": "transition-timing-function: cubic-bezier(0.4, 0, 1, 1)",
    "chai-ease-out": "transition-timing-function: cubic-bezier(0, 0, 0.2, 1)",
    "chai-ease-in-out": "transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1)",

    // Misc
    "chai-list-none": "list-style: none",
    "chai-list-disc": "list-style: disc",
    "chai-list-decimal": "list-style: decimal",
    "chai-object-cover": "object-fit: cover",
    "chai-object-contain": "object-fit: contain",
    "chai-object-center": "object-position: center",
    "chai-whitespace-nowrap": "white-space: nowrap",
    "chai-whitespace-pre": "white-space: pre",
    "chai-whitespace-pre-wrap": "white-space: pre-wrap",
    "chai-z-auto": "z-index: auto",
};
